# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QSegmentAnything
                                 A QGIS plugin
 META AI's Segment Anything (SAM) QGIS integration
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-04-21
        copyright            : (C) 2023 by Efstathios Lymperis
        email                : geo.elymperis@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QSegmentAnything class from file QSegmentAnything.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qgs_segment_anything import QSegmentAnything
    return QSegmentAnything(iface)
